apiVersion: v1
kind: Service
metadata:
  name: api-simples-service
  namespace: teste-deploy
spec:
  type: ClusterIP
  selector:
    app: api-simples
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
