apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: teste-deploy
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: app_db
  DB_USER: postgres
  DB_PASSWORD: password
  DB_NAME: app_db
